name: Deploy VPC Quarantine solution

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: cfn-pipeline-deploy
          template: cfn-deploy.yaml
          no-fail-on-empty-changeset: "1"
