name: Deploy VPC Quarantine solution

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy stack
        run: |
             aws cloudformation deploy \
             --template-file template.yaml \
             --stack-name QUARANTINE-VPC-SOLUTION \
             --parameter-overrides Ec2ImageID=ami-0d421d84814b7d51c \
                                   UserData=$(base64 -w0 user-data.sh) \
             --no-fail-on-empty-changeset
